app/blueprints/auth.py
from flask import Blueprint,url_for,redirect,render_template,request,jsonify
from flask_login.utils import current_user,login_user,login_required,logout_user
from app.models import User,Profile,Plan,Language
from app import db

auth_bp=Blueprint('auth',__name__)

@auth_bp.route('/',methods=['GET','POST'])
def log_in():
    if current_user.is_active:
        return redirect(url_for('home'))
    if request.method == 'GET':
        return render_template('outside/login.html',title="LOGIN")
    if request.method == 'POST':
        body=request.get_json()
        if body['username'] != '':
            user=User.query.filter_by(username=body['username']).first()
            if user is None or not user.check_password(body['password']): #if user exists
                return jsonify({'message':'Wrong data'}),404
            login_user(user,remember=False)
            return jsonify({'message':'All ok'}),200
        return jsonify({'message':'You must provide an username'}),404

@auth_bp.route('/sign_up',methods=['GET','POST'])
def sign_up():
    if request.method == 'GET':
        plans=Plan.query.all()
        languages=Language.query.all()
        return render_template('outside/sign_up.html',title="SIGNUP",
            plans=plans, languages=languages)
    if request.method == 'POST':
        body=request.get_json()
        username=body['username']
        if User.query.filter_by(username=username).first() is None:
            email=body['email']
            password=body['password']
            plan_id=body['plan']
            new_user=User(username=username,email=email,plan_id=plan_id)
            new_user.set_password(password=password)
            db.session.add(new_user)
            db.session.commit()
            new_profile=Profile(user_id=new_user.id,profile_name=username,
                language_id=body['language'],rate_id=1)
            db.session.add(new_profile)
            db.session.commit()
            return jsonify({'message':'User created'}),201
        return jsonify({'message':'Username already taken'}),200

@auth_bp.route('/log_out')
@login_required
def log_out():
    logout_user()
    return redirect(url_for('auth.log_in'))

app/blueprints/home.py
from app.models import Movie,Profile,Serie
from flask import Blueprint,request,render_template
from flask_login.utils import current_user,login_required

home_bp=Blueprint('home',__name__)

@home_bp.route('/')
@login_required
def home():
    profile=request.args.get('profile')
    profiles=Profile.query.filter_by(user_id=current_user.id)
    current_profile=profiles[0] if profile is None \
        else Profile.query.filter_by(profile_name=profile).filter(Profile.user_id == current_user.id).first()
    
    if current_profile is None:
        return render_template('inside/profile_not_found.html',title='HOME',profiles=profiles)

    movies=Movie.query.filter_by(rate_id=current_profile.rate_id)
    series=Serie.query.filter_by(id_rate=current_profile.rate_id)

    return render_template('inside/home.html',
        title='HOME',
        current_profile=current_profile,
        profiles=profiles,
        movies=movies,
        series=series)

app/blueprints/images.py
from flask import Blueprint,send_from_directory
from flask_login import login_required
from config import Config

images=Blueprint('images',__name__)
@images.route('/profile/<image>')
def profile_img(image):
    return send_from_directory(Config.UPLOAD_FOLDER,image)
@images.route('/movie/<image>')
def movie_img(image):
    return send_from_directory('{}/movies'.format(Config.IMGS_FOLDER),image)
@images.route('/serie/<image>')
def serie_img(image):
    return send_from_directory('{}/series'.format(Config.IMGS_FOLDER),image)

app/blueprints/profiles.py
import os
from config import Config
from app import db 
from app.models import Language, Plan,Profile,Rate,User
from flask_login import current_user,login_required
from flask import Blueprint,render_template,request,redirect,url_for,jsonify,abort

router=Blueprint('profiles',__name__)

@router.route('/create',methods=['GET','POST'])
@login_required
def create_profile():
    if request.method == 'GET':
        languages=Language.query.all()
        rates=Rate.query.all()
        return render_template('inside/add_profile.html',title='CREATE A NEW PROFILE',languages=languages,rates=rates)
    if request.method == 'POST':
        profilename=request.form['profilename']
        profile=Profile.query.filter_by(profile_name=profilename).first()
        if not profile is None:
            return jsonify({'message':'The profile name is already taken'}),200
        language=request.form['language']
        rate=request.form['rate']
        image=request.files['image']
        if image.filename != '':
            extension=image.filename.split('.')[1]
            if extension in ['jpg','png']:
                new_profile=Profile(profile_name=profilename,user_id=current_user.id,
                    rate_id=rate,language_id=language,img_path=image.filename)
                try:
                    image.save(os.path.join(
                        os.path.join('app',Config.UPLOAD_FOLDER),
                        image.filename
                    ))
                except FileNotFoundError:
                    print("Error")
                db.session.add(new_profile)
                db.session.commit()
                return jsonify({'message':'New profile created'}),201

        profile_name=request.form['profile_name']
        new_profile=Profile(user_id=current_user.id,profile_name=profile_name)
        db.session.add(new_profile)
        db.session.commit()
        return redirect(url_for('profiles.profiles'))

@router.route('/<id>',methods=['GET'])
@login_required
def profile_by_id(id):
    profile_data=Profile.query.get(int(id))
    print('-*8',profile_data.language_id)
    language=Language.query.get(profile_data.language_id)
    languages=Language.query.all()
    plan=Plan.query.get(int(User.query.get(int(current_user.id)).plan_id)).plan_name
    # rate=Rate.query.get(profile_data.rate_id).letter
    return render_template('inside/profile_data.html',profile=profile_data,
            language=language,languages=languages,plan=plan)

@router.route('/update/<id>',methods=['GET','PUT'])
def update_profile(id):
    if request.method == 'GET':
        profile=Profile.query.filter_by(id=id).first()
        if profile is None:
            return abort(404)
        return jsonify({'profile_name':profile.profile_name,'language':profile.language_id}),200
    
    if request.method == 'PUT':
        profilename=request.form['profilename']
        language=request.form['language']
        profile=Profile.query.filter_by(id=id).first()
        profile.profile_name=profilename
        profile.language_id=language
        image=request.files['image']
        if image.filename != '':
            name,extension=image.filename.split('.')
            if extension in ['jpg','png']:
                profile.img_path=image.filename
                try:
                    image.save(os.path.join(
                        os.path.join('app',Config.UPLOAD_FOLDER)
                        ,image.filename))
                except FileNotFoundError:
                    print(os.path.join(Config.UPLOAD_FOLDER,image.filename),'did not exists')
        db.session.commit()
        db.session.close()
        return jsonify({'message':'User updated'}),203

@router.route('/delete/<id>',methods=['DELETE'])
def delete_profile(id):
    profile=Profile.query.get(int(id))
    if profile is None:
        return jsonify({'message':'Profile not found'}),404
    db.session.delete(profile)
    db.session.commit()
    return jsonify({'message':'Profile successfull deleted'}),200

app/blueprints/search.py
from flask import Blueprint,request,jsonify
from flask.templating import render_template
from app.models import Movie, Rate, Serie

search_bp=Blueprint('search',__name__)

@search_bp.route('/')
def search():
    rates=Rate.query.all()
    return render_template('inside/search.html',title='SEARCH MOVIE',rates=rates)

@search_bp.route('/content')
def search_by_name():
    content_name=request.args.get('cn')
    rate=request.args.get('r')
    movies=Movie.query.filter(Movie.movie_name.like('{}%'.format(content_name))) \
        .filter(Movie.rate_id == rate)
    series=Serie.query.filter(Serie.serie_name.like('{}%'.format(content_name))) \
        .filter(Serie.id_rate == rate)
    return jsonify(movies=[m.serialize for m in movies],series=[s.serialze for s in series])

app/templates/inside/add_profile.html
{% extends 'inside/base.html' %}
{% include 'inside/header_profile.html' %}
{% block content %}
<div class="row justify-content-center align-items-center h-100">
    <div class="col col-sm-6 col-md-6 col-lg-8 col-xl-8">
                <form action="{{ url_for('profiles.create_profile') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                <input id="id" value="<?php echo $rows['Id'] ?>" name="id" hidden/>
                    <label for="profilename">Profile name</label>
                    <p id="perfil_existe" class="alert alert-danger" hidden>Ya existe ese usuario</p>
                    <input id="nombre_oculto" name="nombre_oculto" value="<?php echo $rows['Nombre']?>" hidden/>
                    <input type="text" name="profilename" id="profilename" class="form-control"/>
                </div>
                
                <div class="form-group">
                    <label for="rate">Rate:</label>
                    <select id="rate" name="rate" class="form-control" >
                    {% for rate in rates %}
                        <option value="{{ rate.id }}">{{ rate.letter }}</option>
                    {% endfor %}
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="language">Languages</label>
                    <select id="language" name="language" class="form-control">
                        {% for language in languages %}
                        <option value="{{ language.id }}">{{ language.language }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="image">Selecciona la imagen:</label>
                    <input type="file" name="image" id="image" accept="image/*"/>
                </div>
                <input type="submit" class="btn btn-primary" name="create" value="CREATE" id="create"/>
                </form>
            </div>
    </div>
            <div class="container my-1">
            <br><br><br><br><br><br>
            </div>
            <script src="/static/js/createProfile.js"></script>
{% endblock %}

app/templates/inside/base.html
{% include 'base/head.html' %}
<body>
    {% block content %} {% endblock %}
    {% include 'base/footer.html' %}
</body>

app/templates/inside/create_profile.html
{% extends 'base.html' %}
{% block content %}
<form action="{{ url_for('profiles.create_profile') }}" method="post">
    <div>
        <label for="profile_name">Profile name:</label>
        <input type="text" name="profile_name" id="profile_name">
    </div>
    <input type="submit" value="CREATE">
</form>
{% endblock %}

app/templates/inside/header.html
<header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand mr-auto" href="#">
            <img src="/static/imgs/logo.png" alt="" style="width: 40px;">Peliculas 
        </a>
        <ul class="navbar-nav">
            <li class="nav-item mr-2">
                {% if current_profile is defined %}
                    <a href="{{ url_for('profiles.profile_by_id',id=current_profile.id) }}" class="text-white">
                    <img src="{{ url_for('images.profile_img',image=current_profile.img_path) }}" alt="Foto de perfil" width="40px"/>
                    {{ current_profile.profile_name }}
                {% endif %}
            </a>    
            </li>
            
            <li class="nav-item">
                <div class="dropdown">
                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">Profiles</button>
                    <div class="dropdown-menu">
                        {% for profile in profiles %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('home.home') }}?profile={{ profile.profile_name }}">
                                <img class="rounded-circle img-fluid mx-2" src="{{ url_for('images.profile_img',image=profile.img_path) }}" width="40px;"/>
                                {{ profile.profile_name }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </li>
            <li class="nav-item">        
                <a class="nav-link" href="{{  url_for('search.search') }}">
                    <img src="/static/imgs/magnifyging_glass.png" alt="search">
                </a>
            </li>
            <li class="nav-item">
                <a class="text-white" href="{{ url_for('auth.log_out') }}">Cerrar sesión</a>
            </li>
            
        </ul>
    </nav>
</header>

app/templates/inside/header_home.html
<header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand mr-auto" href="#">
            <img src="/static/imgs/logo.png" alt="" style="width: 40px;">Peliculas 
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#planes" class="nav-link">Planes</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">¿Quiénes somos?</a>
            </li>
            <li>
                <a href="{{ url_for('profiles.profile_by_id',id=current_profile.id) }}">Editar perfil</a>
            </li>
            <li class="nav-itm">
                <div class="dropdown">
                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">Perfiles</button>
                    <div class="dropdown-menu">
                    {% for profile in profiles %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ url_for('home') }}?profile={{ profile.profile_name }}"><img class="rounded-circle img-fluid mx-2" src="" width="40px;"/>{{ profile.profile_name }}</a>
                    {% endfor %}
                    </div>
                </div>
            </li>
            <li class="nav-item mx-2">        
                <a href="{{ url_for('log_out') }}">Cerrar sesión</a>
            </li>
            <li class="nav-item mx-4">        
                <a class="nav-link" href="#">
                    <img src="/static/imgs/magnifyging_glass.png" alt="search">
                </a>
            </li>
        </ul>
    </nav>
</header>

app/templates/inside/header_profile.html
<header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-expand-sm bg-dark navbar-dark fixed-top">
        <a class="navbar-brand mr-auto" href="#">
            <img src="/static/imgs/logo.png" alt="" style="width: 40px;">Peliculas 
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#planes" class="nav-link">Planes</a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">¿Quiénes somos?</a>
            </li>
            <li class="nav-itm">
                <div class="dropdown">
                    <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">Perfiles</button>
                    <div class="dropdown-menu">
                    {% for profile in profiles %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ url_for('home') }}?profile={{ profile.profile_name }}"><img class="rounded-circle img-fluid mx-2" src="" width="40px;"/>{{ profile.profile_name }}</a>
                    {% endfor %}
                    </div>
                </div>
            </li>
            <li class="nav-item mx-2">        
                <a href="{{ url_for('log_out') }}">Cerrar sesión</a>
            </li>
            <li class="nav-item mx-4">        
                <a class="nav-link" href="#">
                    <img src="/static/imgs/magnifyging_glass.png" alt="search">
                </a>
            </li>
        </ul>
    </nav>
</header>

app/templates/inside/home.html
{% extends 'inside/base.html' %}
{% include 'inside/header.html' %}
{% block content %}
<div class="container-fluid my-auto">
  <br><br>
  <h2 class="display-4">Welcome, {{ current_profile.profile_name }}</h2>
  <div class="container">
  <h2 class="display-4">Sigue viendo...</h2>
  <!--Carousel Wrapper-->
<div id="carousel-example-2" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <div class="view">
              <img class="d-block carousel-inner" src="{{ url_for('images.movie_img',image=movies[0].movie_img_path)}}"
                alt="First slide">
              <div class="mask rgba-black-light"></div>
            </div>
            <div class="carousel-caption">
              <h3 class="h3-responsive">{{ movies[0].movie_name }}</h3>
              <p>{{ movies[0].rate_id }}</p>
            </div>
          </div>
    {% for movie in movies[1:] %}
      <div class="carousel-item justify-content-center">
        <div class="view">
          <img class="d-block carousel-inner" src="{{ url_for('images.movie_img',image=movie.movie_img_path)}}"
            alt="First slide">
          <div class="mask rgba-black-light"></div>
        </div>
        <div class="carousel-caption">
          <h3 class="h3-responsive">{{ movie.movie_name }}</h3>
          <p>{{ movie.rate_id }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-2" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-2" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
  <!--/.Carousel Wrapper-->

    <br>
    <br>
    <br>
    <div class="container mt-5">
    
        <p class="h3">O sigue con tus...</p>
    </div>
    <div class="container text-center">
        <h3 class="display-">Programas</h3>
    <div class="row">
      {% for serie in series %}
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="{{ url_for('images.serie_img',image=serie.serie_img_path) }}" alt="...">
        <div class="caption" id="img">
            <h3>Nombre: {{ serie.serie_name }}</h3>
            <p>Duracion: {{ serie.length }}</p>
            <p>Capitulo: {{ serie.chapter_number }}</p>
            <p>Clasificacion: {{ serie.id_rate }}</p>
        </div>
        </div>
    </div>
    {% endfor %}
    </div>
    <h3 class="display-5">Peliculas</h3>
    <div class="row">
      {% for movie in movies %}
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
        <img src="{{ url_for('images.movie_img',image=movie.movie_img_path) }}" alt="...">
        <div class="caption" id="img">
            <h3>Nombre: {{ movie.movie_name }}</h3>
            <p>Duracion: {{ movie.length }}</p>
            <p>Clasificacion: {{ movie.rate_id }}</p>
        </div>
        </div>
    </div>
    {% endfor %}
    </div>
    </div>

</div>
<p> 
</p>
{% endblock %}

app/templates/inside/profile_base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script> 
    <title>{{ title }}</title>
    <style>
        .carousel-inner img {
            width: 334px;
            height: 445px;
        }
        .thumbnail img{
            width: 326px;
            height: 480px;
        }
    </style>
</head>
<body>
    <header class="mb-5">
        <nav class="navbar navbar-expand-lg navbar-expand-sm bg-dark navbar-dark fixed-top">
            <a class="navbar-brand mr-auto" href="#">
                <img src="/static/imgs/logo.png" alt="" style="width: 40px;">Peliculas 
            </a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#planes" class="nav-link">Planes</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">¿Quiénes somos?</a>
                </li>
                <li class="nav-item mx-2">        
                    <a href="{{ url_for('log_out') }}">Cerrar sesión</a>
                </li>
                <li class="nav-item mx-4">        
                    <a class="nav-link" href="#">
                        <img src="/static/imgs/magnifyging_glass.png" alt="search">
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}
    <footer class="bg-dark mt-4">
        <div class="container">
            <div class="row justify-content-center align-items-center minh-100">
                <img width="64px" src="../imgs/logo.png" alt="logo"/>
            </div>
            <div class="row justify-content-center align-items-center minh-100">
                <div class="col-*-*">
                    <ul class="list-inline text-white">
                        <li class="list-inline-item">Términos y Aviso de privacidad</li>
                        <li class="list-inline-item">Cometarios</li>
                        <li class="list-inline-item">Sugerencias</li>
                    </ul>
                </div>
                <div class="col-3">
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <img src="../imgs/png/001-facebook.png"/>
                        </li>
                        <li class="list-inline-item">
                            <img src="../imgs/png/002-twitter.png" alt=""></li>
                        <li class="list-inline-item">
                            <img src="../imgs/png/004-instagram-bosquejado.png" alt="">
                        </li>
                        <li class="list-inline-item">
                            <img src="../imgs/png/003-youtube.png" alt="">
                        </li>
                    </ul>
                </div>

                </div>
            </div>
                </ul>
            </div>
            <!--<div class="text-white">Iconos diseñados por <a href="https://www.flaticon.es/autores/pixel-perfect" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.es/"     title="Flaticon">www.flaticon.com</a></div><div class="text-white">Iconos diseñados por <a href="https://www.flaticon.es/autores/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.es/"     title="Flaticon">www.flaticon.com</a></div>
            Iconos diseñados por <a href="https://www.flaticon.es/autores/xnimrodx" title="xnimrodx">xnimrodx</a> from <a href="https://www.flaticon.es/" title="Flaticon"> www.flaticon.es</a>
        </div>-->
    </footer>
    <script src="../js/busqueda_pel_pro.js"></script>
</body>




<!-- 
    INSERT INTO `pelicula` (`Nombre`, `Duracion`, `Portada`, `Clasificacion`) VALUES ('1917', '01:35:02', 'imgPeliculas/1917.jpg', 'B15'), ('Arkansas', '01:02::04', 'imgPeliculas/Arkansas.jpg', 'B'), ('La llegada', '01:05:00', 'imgPeliculas/Arrival.jpg', 'A'), ('El ultimo deseo', '01:20:03', 'imgPeliculas/Deseo.jpg', 'C'), ('Escape de Pretoria', '02:04:00', 'imgPeliculas/Escape.jpg', 'B15'), ('Mision rescate', '01:15:20', 'imgPeliculas/Mision.jpg', 'B15'), ('Sonic - La pelicula', '01:02:30', 'imgPeliculas/Sonic.jpg', 'A'), ('Sputnik', '01:20:02', 'imgPeliculas/Sputnik.jpg', 'C'); -->
</html>

app/templates/inside/profile_data.html
{% extends 'inside/base.html' %}
{% include 'inside/header_profile.html' %}
{% block content %}
<br>
<h2>Editar perfil</h2>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="container">
                    <div class="card  bg-ligth border-dark" style="width:400px">
                        <img class="card-img-top" src="{{ url_for('images.profile_img',image=profile.img_path) }}" alt="{{ profile.img_path }}" style="width:100%">
                        <div class="card-body">
                            <h4 class="card-title">{{ profile.profile_name }}</h4>
                            <p class="card-text">Usuario tipo: {{ plan }}</p>
                            <button class="btn btn-primary  w-100" id="editar_">Editar perfil</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col mb-5">
                <form action="{{ url_for('profiles.update_profile',id=profile.id) }}" method="post" enctype="multipart/form-data">
                <div class="md-form">
                    <label for="usuario">Nombre de perfil</label>
                    <p id="perfil_existe" class="alert alert-danger" hidden>Ya existe ese usuario</p>
                    <input id="nombre_oculto" name="nombre_oculto" hidden value="<?php echo $rows['Nombre']?>" />
                    <input type="text" name="profilename" id="profilename" class="form-control mdb-autocomplete" value="{{ profile.profile_name }}"/>
                </div>
                
                <div class="form-group">
                    <label for="language">Idioma de tu preferencia</label>
                    <select id="language" name="language" class="form-control" >
                        <option value="{{ language.id}}" selected disabled >Current laguage - {{ language.language }}</option>
                        {% for language in languages %}
                        <option value="{{ language.id }}">{{ language.language }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="Imagen">
                        Selecciona la imagen: 
                    </label>
                    <input type="file" name="image" id="image" accept="image/all"/>
                </div>
                <input type="submit" class="btn btn-success" value="Guardar" id="guardar"  />
                </form>
                <div>
                    <a href="{{ url_for('profiles.create_profile')}}"><button class="btn btn-warning">Añadir perfil</button></a>
                </div>
                <div>
                    <a href="{{ url_for('profiles.delete_profile',id=profile.id) }}"><button class="btn btn-info" id="delete_profile">Eliminar perfil</button></a>
                </div>
            </div>
    </div>
    <div class="container">
        <br>
        <br>
    </div>
    <script src="/static/js/updateProfile.js"></script>
    <script src="/static/js/deleteProfile.js"></script>
{% endblock %}

app/templates/inside/profile_not_found.html
{% extends 'inside/base.html' %}
{% include 'inside/header.html' %}
{% block content %}
<br><br><br><br>
<h1 class="text-center">THE PROFILE DOES NOT EXIST IN THIS USER</h1>
{% endblock %}

app/templates/inside/search.html
{% extends 'inside/base.html' %}
{% block content %}
<div class="container">
    <div class="row mb-5">
        <div class="col-9">
            <label for="search">Type movie/serie's name</label>
            <input class="form-control" type="text" id="search" name="search"/>
        </div>
        <div class="col">
            <label for="rate">Rate</label>
            <select name="rate" id="rate" class="form-control text-center">
                <option value="" selected></option>";
                {% for rate in rates %}
                    <option value="{{ rate.id }}"> {{ rate.letter }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    
    <div class="row">
        <div id="wrapper-movies"></div>
    </div>
    
    <div class="row">
        <div id="wapper-series"></div>
    </div>
</div>
{% endblock %}