app/blueprints/auth.py
from flask import Blueprint,url_for,redirect,render_template,request,jsonify
from flask_login.utils import current_user,login_user,login_required,logout_user
from app.models import User,Profile,Plan,Language
from app import db

auth_bp=Blueprint('auth',__name__)

@auth_bp.route('/',methods=['GET','POST'])
def log_in():
    if current_user.is_active:
        return redirect(url_for('home'))
    if request.method == 'GET':
        return render_template('outside/login.html',title="LOGIN")
    if request.method == 'POST':
        body=request.get_json()
        if body['username'] != '':
            user=User.query.filter_by(username=body['username']).first()
            if user is None or not user.check_password(body['password']): #if user exists
                return jsonify({'message':'Wrong data'}),404
            login_user(user,remember=False)
            return jsonify({'message':'All ok'}),200
        return jsonify({'message':'You must provide an username'}),404

@auth_bp.route('/sign_up',methods=['GET','POST'])
def sign_up():
    if request.method == 'GET':
        plans=Plan.query.all()
        languages=Language.query.all()
        return render_template('outside/sign_up.html',title="SIGNUP",
            plans=plans, languages=languages)
    if request.method == 'POST':
        body=request.get_json()
        username=body['username']
        if User.query.filter_by(username=username).first() is None:
            email=body['email']
            password=body['password']
            plan_id=body['plan']
            new_user=User(username=username,email=email,plan_id=plan_id)
            new_user.set_password(password=password)
            db.session.add(new_user)
            db.session.commit()
            new_profile=Profile(user_id=new_user.id,profile_name=username,
                language_id=body['language'],rate_id=1)
            db.session.add(new_profile)
            db.session.commit()
            return jsonify({'message':'User created'}),201
        return jsonify({'message':'Username already taken'}),200

@auth_bp.route('/log_out')
@login_required
def log_out():
    logout_user()
    return redirect(url_for('auth.log_in'))

app/templates/outside/base.html
{% include 'base/head.html' %}
<body>
    {% include 'outside/header.html' %}
    {% block content %} {% endblock %}
    {% include 'base/footer.html' %}
</body>
</html>

app/templates/outside/header.html
<header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand mr-auto" href="index.html">
            <img src="/static/imgs/logo.png" alt="" style="width: 40px;">
            Peliculas 
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <button class="btn btn-primary">
                    <a href="#" class="text-white">
                    Prueba gratis
                    </a>
                </button>
            </li>

            <li class="nav-item">
                <a href="#planes" class="nav-link">
                    Planes
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    ¿Quiénes somos?
                </a>
            </li>
            
        </ul>
    </nav>
</header>

app/templates/outside/login.html
{% extends 'outside/base.html' %}
{% block content %}
<div class="container h-100 align-items-center">
    <div class="row">
        <div class="col mt-2">
            <div class="row">
                <h2 class="display-4 text-dark">Identifiquese para entrar</h2>
            </div> 
            <div class="row h-50 align-items-center text-dark">
                <div class="col">
                    <form action="{{ url_for('auth.log_in') }}" method="POST" id="ingresar">
                        <div class="form-group">
                            <label for="username">Usuario</label>
                            <input type="text" name="username" id="username" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label for="password">Contraseña</label>
                            <input type="password" name="password" id="password" class="form-control" />
                        </div>
                        <input type="submit" class="btn btn-danger" value="LOG IN"></input>
                    </form>
                </div>
            </div>
            <div class="row justify-content-center">
                <p >No tienes cuenta <a href="{{ url_for('auth.sign_up') }}" >Registrate</a></p>
                <div class="container justify-content-center" style="display: none;" id="error"></div>
            </div> 
            <div id="sin_sesion"></div>
        </div>
        <div class="col">
            <img src="/static/imgs/logo_footer.png" class="img-fluid" alt="">
        </div>
    </div>
</div>
<script defer src="/static/js/login.js"></script>
{% endblock %}
</body>

app/templates/outside/sign_up.html
{% extends 'outside/base.html' %}
{% block content %}

<div class="mx-auto container-fluid  h-100 align-items-center p-4 mb-4">
    <div class="container">
    <div class="row text-center">
        <h2 class=" text center">Sea parte de nuestra comunidad</h2>
    </div>
    <div class="row mx-auto">
        <div class="col mt-2">
            <form action="" method="POST" id="sign-up-form">
            <div class="form-group">
                <p id="existe"></p>
                <label for="username">Nombre de username:</label>
                <input type="text" name="username" class="form-control" id="username"/>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" name="email" class="form-control" id="email" />
            </div>
            <div class="form-group">
                <label for="password">Contraseña:</label>
                <input type="password" name="password" class="form-control" id="password" />
            </div>
            <div class="form-group">
                <label for="language">Selecciona el idioma de tu preferencia</label>
                <select name="language" id="language" class="form-control">
                    <option value="" class="form-control">Select an element</option>
                    {% for language in languages %}
                        <option value="{{ language.id }}" class="form-control">{{ language.language }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="plan">Selecciona el plan de tu preferencia</label>
                <select name="plan" id="plan" class="form-control">
                    <option value="" class="form-control">Select an element</option>
                    {% for plan in plans %}
                    <option value="{{ plan.id }}" class="form-control">{{ plan.plan_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <p id="mensaje"></p>
            <input type="submit" class="btn btn-primary" id="sign-up" value="SIGN UP"/>
            <p>Return to <a href="{{ url_for('auth.log_in') }}">log in</a></p>
        </form>
        </div>
    </div>
</div>
</div>
<br>
<script src="/static/js/signup.js"></script>
{% endblock %}